### ISSUE TITLE
error in python tools\set_up_db.py

### ISSUE THREAD

**Issue by HTOR3** [jpwright/enmodal#26]
When I follow the 'Run database setup tool' step in command prompt,
I get the following error:

(venv) C:\Users\hugho\Downloads\enmodal>python server.py
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from EnmodalCore import enmodal
  File "C:\Users\hugho\Downloads\enmodal\EnmodalCore.py", line 27, in <module>
    import Transit
  File "C:\Users\hugho\Downloads\enmodal\lib\transit\Transit.py", line 2, in <module>
    import TransitGIS
  File "C:\Users\hugho\Downloads\enmodal\lib\transit\TransitGIS.py", line 17, in <module>
    DGGRID_HOST = config.get('dggrid', 'host')
  File "c:\python27\Lib\ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'dggrid'

**Comment by anish3343** [comment]
did you create the settings.cfg file?

**Comment by HTOR3** [comment]
Thanks! I've fixed it!

**Comment by MisterVideosoEx** [comment]
What was the fix? I have almost the same error and can't figure it out, and yes, I have a settings.cfg file
