### ISSUE TITLE
Redis URL error when starting server

### ISSUE THREAD

**Issue by MattKaza** [jpwright/enmodal#27]
Hello,
I am using Py3 and Win10, 
And when I try to run server.py on cmd, I get:

```
 Traceback (most recent call last):
  File "server.py", line 54, in <module>
    redis_store = FlaskRedis(app)
  File "C:\Users\matan\venv\lib\site-packages\flask_redis\__init__.py", line 20, in __init__
    self.init_app(app)
  File "C:\Users\matan\venv\lib\site-packages\flask_redis\__init__.py", line 42, in init_app
    redis_url, **self.provider_kwargs
  File "C:\Users\matan\venv\lib\site-packages\redis\client.py", line 602, in from_url
    connection_pool = ConnectionPool.from_url(url, db=db, **kwargs)
  File "C:\Users\matan\venv\lib\site-packages\redis\connection.py", line 920, in from_url
    'schemes (%s)' % valid_schemes)
ValueError: Redis URL must specify one of the followingschemes (redis://, rediss://, unix://)
```

I have manually changed print statements all over the code to work on Py3 so that might be related

Thanks in advance!

**Comment by MattKaza** [comment]
Okay, for anyone with the same problem:

I went to C:\Users\USER\venv\Lib\site-packages\flask_redis, and changed row 37 to `'{0}_URL'.format('redis')` at it seems to work for me
good luck tho
