### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by Dezlite** [jpwright/enmodal#35]
**I'm trying to get enmodal to work on my Windows. I installed Python 3.9.1 instead of 2.7 like the guide asked. The reason is that on version 2.7 I couldn't find the "Add Python to system PATH" on it. When I got 3.9.1, I found that option easily. I did everything and then made it up to the part where you need to install these four commands:** 
`pip install virtualenv`
`virtualenv venv`
`venv\Scripts\activate.bat`
`pip install -r requirements.txt`
**I did the first three successfully, but then the fourth one gave me issues. I got this extremely large error in red:**
`ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\Downloads\enmodal\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-9bpfbbop\\cffi_37f00589138648e386ff60201594ab0c\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-9bpfbbop\\cffi_37f00589138648e386ff60201594ab0c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-siz2bfmb'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-9bpfbbop\cffi_37f00589138648e386ff60201594ab0c\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-9bpfbbop\cffi_37f00589138648e386ff60201594ab0c\setup.py", line 116, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\user\AppData\Local\Temp\pip-install-9bpfbbop\cffi_37f00589138648e386ff60201594ab0c\setup.py", line 94, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "c:\users\user\appdata\local\programs\python\python39\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\user\appdata\local\programs\python\python39\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\users\user\appdata\local\programs\python\python39\lib\distutils\_msvccompiler.py", line 323, in compile
        self.initialize()
      File "c:\users\user\appdata\local\programs\python\python39\lib\distutils\_msvccompiler.py", line 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\user\Downloads\enmodal\venv\lib\site-packages\setuptools\msvc.py", line 312, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\user\Downloads\enmodal\venv\lib\site-packages\setuptools\msvc.py", line 266, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`
**I also got this error in orange and here's what that one read:**
`WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the 'C:\Users\mmdes\Downloads\enmodal\venv\Scripts\python.exe -m pip install --upgrade pip' command.`
**I attempted to go to that director and run the command, but no luck, it just gave me syntax errors for some reason. Any help here is appreciated.**

**Comment by Dezlite** [comment]
**UPDATE 1**
I scrolled down and realized that you're actually supposed to only use Python 2.7. It only says that under the Mac and Ubuntu tutorials for some reason, so I was unable to see it in the Windows section. I assumed that using 3.9.1 caused this error, so I uninstalled it.
Anyways, I deleted Python version 3.9.1 and went back to 2.7. The problem with version 2.7 is that the "_Add Python to system PATH_" option is just **NOT THERE** on the 2.7 installer. It is nowhere to be found, but on 3.9.1, it can be seen in the lower left-hand corner when attempting to install that version. So, I did research and found out how to manually add Python to the PATH. I did what I could and I went back to Command Prompt to execute the code. However, another problem came up. When I input `pip install virtualenv`, Command Prompt doesn't know what PIP is anymore, and tells me the following: `'pip' is not recognized as an internal or external command, operable program or batch file.` I am very confused right here.

**Comment by Dezlite** [comment]
**UPDATE 2**
I did more research and found out that PIP is not bundled with Python 2.7, and it is actually bundled with the newer versions, which is why I didn't get this error on 3.9.1. Anyway, I looked at tutorials on how to get PIP and I downloaded a file called `get-pip.py` and put it in `C:\Python27`. I went into the command prompt and typed in `python get-pip.py`. As it worked, I got a message that read `DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.` As soon I saw this a lost hope because Python 2.7 will be impractical by literally next month, which is bad since only version 2.7 can work. I waited and then the PIP installation failed. The final error read `ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip`
Well, there's probably nothing I can do now.

**Comment by Dezlite** [comment]
**UPDATE 3**
I got the idea of using the PIP from version 3.9.1, and then installing 2.7, but that didn't work, the program asked for the new version of Python in order to continue. Then I remembered that version 2.7.9 actually HAS PIP bundled with it. And since it is still part of version 2.7, I thought I had a chance here. So I successfully installed it and PIP, and I went to go execute the commands. However, there were STILL ISSUES! 
When I typed in `virtualenv venv`, it tried to work, and then I got an error that said `ImportError: No module named importlib_metadata`. 
I decided to ignore that error. Then I finally got to the `pip install -r requirements.txt` command. When I typed it in I got a message that read `No Python at 'c:\program files\python39\python.exe'` I was really confused here. The program was looking for Python 3.9, which I uninstalled. The run database setup tool command also gave this error. I deleted the python 39 folders, so hopefully, the program will try to locate version 2.7.9. Same error. For some odd reason, the program was searching for version 3.9. Well, time to do even more research...

**Comment by Dezlite** [comment]
**UPDATE 4**
It's been a couple of days. I figured out why I got the message that read `No Python at 'c:\program files\python39\python.exe'`. The reason why was because I still had Python 3.9 in my PATH, so I removed that. I'm using Python 2.7.9, and that's because it's the last version of 2.7 that has PIP bundled with it during the installation. I did research, and I found out that it is actually **IMPOSSIBLE** to get PIP on earlier versions of 2.7, with this Youtube video: `https://youtu.be/Ko9b_vC6XY0`. So with Python 2.7.9, I can use the native version of PIP. However, there are still errors that occur with this version. That's right, there are STILL ERRORS!
Typing `pip install -r requirements.txt` results in `Command python setup.py egg_info failed with error code 1 in c:\users\user\appdata\local\temp\pip_build_mmdes\cffi Storing debug log for failure in C:\Users\user\pip\pip.log`.
Typing `python tools\set_up_db.py` results in `ImportError: No module named psycopg2`.
And finally, `python server.py` results in `ImportError: No module named flask`.
Anyway, I will research how to fix these new problems, and I will get back with another UPDATE. So far, this is the most progress to getting enmodal working on my machine.

**Comment by Dezlite** [comment]
**UPDATE 5**
I figured out that there are NEWER versions of Python 2. I got Python 2.7.18, which is the REAL actual last release of Python 2, and I believed that 2.7.9 was the last release, so I had hoped with 2.7.18.
When I ran the `pip install virtualenv` command, I saw that it installed `importlib-metadata` which was a great sign to see, since that was missing before.
I executed `virtualenv venv` and `venv\Scripts\activate.bat` successfully as well.
I also ran `pip install -r requirements.txt` and it worked as well, it just had to download a bunch of junk, and took quite a while. It did give a small error in RED that said `ERROR: Package 'setuptools' requires a different Python: 2.7.18 not in '>=3.6'`. I am unsure what this means, is it saying that I need Python 3.6? 
I finally got to the end, and there are still issues, sadly, but this is the furthest I have gotten.
Typing `python tools\set_up_db.py` still results in `ImportError: No module named psycopg2`.
And finally, `python server.py` still results in `ImportError: No module named flask`.
I will continue to work on these missing modules that are missing.

**Comment by Dezlite** [comment]
**UPDATE 6: SUCCESS!**
I was on my way to find a solution to the `psycopg2` and `flask` errors from Update 5. I read on StackOverflow that I can run this command: `pip install git+https://github.com/nwcell/psycopg2-windows.git@win32-py25#egg=psycopg2`. It failed, but the Command prompt told me something useful: `ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?`. And I remembered that early in the enmodal guide here, it said something about installing Git, but I believed that it wasn't mandatory, so I installed Git. I re-ran the command, and it STILL GAVE me the error that it couldn't find psycopg2. I also ran `    pip install psycopg2` and guess what? it still gave me the error. I continued to run the command and it tells me `Requirement already satisfied: psycopg2 in c:\python27\lib\site-packages (2.5.2)`, so psycopg2 is installed, but STILL ERROR!
I did further research and found a command: `pip install psycopg2-2.6.2-cp27-cp27m-win_amd64.whl` and this one worked. As I read more stuff, I got the random idea to actually re-run the `pip install -r requirements.txt` command one more time since I had GIT, and I did that. **There were NO errors** at all, which was an extremely good sign, other than the prompt telling me to upgrade PIP.
I ran `python tools\set_up_db.py`, and I got an error: `Error: authentication method 10 not supported`, but I ignored it. I ran the final command, and it finally worked! This is a true Christmas gift for me without a doubt. I hope other people who are having trouble read this. But other than that, I'll be playing enmodal!

**Comment by Dezlite** [comment]
**SUMMARY**
Use Python 2.7.18. It is the last version of Python, and it has PIP installed.
Other than that, that's all you need to do besides getting Git, PostgreSQL, and inputting the commands.
The only thing is that pip 21.0 will drop support for Python 2.7 in January 2021, so I have no clue how difficult this will get since it requires 2.7 of Python, but hey, at least it works.
