### ISSUE TITLE
Trying to install on a new mac, getting 127.0.0.1:5050/template issue

### ISSUE THREAD

**Issue by adrianmorquecho** [jpwright/enmodal#55]
So I have enmodal on my old mac (it has Big Sur 11.2.2) and it loads if I type cd to the directory, do "source venv/bin/activate" and "python server.py"

I tried installing it on my new mac (Monterey 12.6.2) on two separate occasions with Python 2.7 and the new Python 3 and I have gotten the same error.

First, when I type "python server.py", it shows:

Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5050/ (Press CTRL+C to quit)

Then, when I go to type in this address in the browser, I get this:

[2022-12-29 22:44:22,190] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/adrianmorquecho/Documents/enmodal/EnmodalCore.py", line 84, in route_main
    return render_template('app.html')
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/adrianmorquecho/Documents/enmodal/venv/lib/python2.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: app.html
127.0.0.1 - - [29/Dec/2022 22:44:22] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [29/Dec/2022 22:44:23] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by adrianmorquecho** [comment]
@jpwright

**Comment by jls83** [comment]
@adrianmorquecho Just ran into the same issue; solved it by running `npm install && grunt` from the `enmodal` directory before running `python server.py`. The items used to be checked in to the repository but were removed in https://github.com/jpwright/enmodal/commit/dfe356eda079feaf14fc0e531cdc111a146ffbd1

**Comment by Valdotorium** [comment]
i fixed the issue by changing the folder the program searches its templates in. in server.py, I changed line 40 to: application = Flask(__name__, static_folder='./src', template_folder='./src', static_url_path='/static')

**Comment by adrianmorquecho** [comment]
Thank you, I was able to fix the issue on my own by just manually
installing the packages that were causing problems.
